### ISSUE TITLE
Format output when editing multiline notes

### ISSUE THREAD

**Issue by sungwoncho** [dnote/cli#121]
The output after editing multiline notes should be formatted better.

*reproduction*

    $ dnote edit js 2
    • new content: multi

    line
    ✔ edited the note

should be something more like

    $ dnote edit js 2
    ---- content ----
    multi

    line
    -----------------
    ✔ edited the note

**Comment by klebervirgilio** [comment]
Can I pick this one up?

**Comment by sungwoncho** [comment]
@klebervirgilio sure, have a look at

https://github.com/dnote/cli/blob/e7940229cf69912f5f6bbe79e4d796f683f318f8/cmd/edit/edit.go#L109
https://github.com/dnote/cli/blob/e7940229cf69912f5f6bbe79e4d796f683f318f8/cmd/add/add.go#L73-L75

**Comment by sungwoncho** [comment]
Fixed by #123. Thank you @klebervirgilio.
