### ISSUE TITLE
Which file to grab to restore my notes

### ISSUE THREAD

**Issue by snoblenet** [dnote/cli#141]
My laptop died and I have to rebuild it from my hard disk backups.

Which file do I grab to restore my dnote notes?

Thanks.

**Comment by sungwoncho** [comment]
Hi @snoblenet, grab `.dnote` directory from your home directory in the old machine and place it in the home directory in your new machine. Incidentally what version are you using?

**Comment by sungwoncho** [comment]
Closing because it was answered. Please reopen if there are problems.
