### ISSUE TITLE
wrong created_at value

### ISSUE THREAD

**Issue by sungwoncho** [dnote/cli#145]
Using v0.4.9,

Reproduce:

▶ dnote v dnote 275
  • book name: dnote
  • note uuid: fb78840a-708f-473f-bcf2-0dc7d9e4ef01
  • created at: Jan 1, 1970 10:00am (AEST)

* Why did it happen?
* Are there other notes with the same problem?

---

happens after syncing

**Comment by michielboekhoff** [comment]
That's strange. Seems like it's not being sent a timestamp maybe? I can't replicate on 0.4.9:

```
$ dnote v foo 1
  • book name: foo
  • note uuid: 90475e8d-dfcb-40df-b89b-bd053d9e66d6
  • created at: Dec 19, 2018 8:32pm (GMT)
```
