### ISSUE TITLE
Proposal for end-to-end encryption

### ISSUE THREAD

**Issue by sungwoncho** [dnote/cli#157]
This is a proposal for end-to-end encryption of notes and books.

## Goal

* Use AES256 in GCM mode as a symmetric cipher.
* Server should not have access to the users' secret key for AES256.
* Despite not having access to the secret key, the server needs to be able to authenticate user.

---

## Proposal

1. User enters email and password.
2. Use PBKDF2 with SHA256 to derive 256 bit secret key, `k0`. (PBKDF is chosen because it is readily available in Web Crypto API which we need for the web client)

```
k0 = pbkdf2(password: password, salt: email, iteration: 10000)
```

3. Derive another key `k1` which is of the same length as `k0`.
  - how many rounds do we need? Is 1 round sufficient because `k0` is pseudo-random anyway?

```
k1 = pbkdf2(password: k0, salt: password, iteration: 1)
```

4. `k1` is sent to the server to authenticate the user. `k0` is  *never* sent to the server.
  - server hashes `k1` using PBKDF2 using 15000 rounds before storing it.
5. Use AES256 in GCM mode using secret key `k0` to encrypt all data before sending to the server.

### Threat model

* Exhaustive search takes ~ 2^256 steps  (Can this number be lower in practice?) Two kinds of attacks:
  * dictionary attack to get `k0` from `k1`
  * brute-force attack to decrypt a given ciphertext with a random key

## Alternative version

1. User enters email and password
2. Derive a key using PBKDF2 with SHA512 to derive a 512 bit key from email/password combination..

```
k = pbkdf2(password: password, salt: email, iteration: 10000)
```

3. Split the derived key into two: `(k0, k1) = (k[0:255], k[256:511])`.
  - `k0` is sent to the server to validate the login. The server hashes the payload again using pbkdf2 with 15000 rounds before storing it.
  - `k1` is *never* sent to the server
4. Use AES256 in GCM mode using the secret key `k1` to encrypt all data in the client side before sending it to the server (Benefit over CBC or CTR mode: GCM mode offers ciphertext integrity.)
  - do we need ciphertext integrity or just confidentiality? (probably we need ciphertext integrity?)

## Alternative version 2

* User enters email and password
* Derive `k` <- pbkdf2(password: password, salt: email, alg: 'sha256', iteration: 10000)
* Derive `k0` <- hkdf(alg: 'sha256', secret: k, salt: email, info: 'enc') (used as encryption key)
* Derive `k1` <- hkdf(alg: 'sha256', secret: k, salt: email, info: 'auth') (sent to server for authentication)
* POST to '/register': (email, k1, kdf_iteration). `k0` is not sent to the server.
  - server hashes `k1` using PBKDF2 using 15000 rounds before storing it.
* Use AES256 in GCM mode using the secret key `k1` to encrypt all data in the client side before sending it to the server (Benefit over CBC or CTR mode: GCM mode offers ciphertext integrity.)

### Threat model

* Exhaustive search takes ~ 2^256 steps  (Can this number be lower in practice?):
  * brute-forcing to decrypt a given ciphertext

---

In both options, the server never learns the secret key used by the client for the symmetric cipher.

### Main question

* Does hashing the key with pbkdf2 with 1 round before sending it to the server provide any additional security? Doing so, we avoid transmitting plain key to the server. But the communication is already happening between two trusted parties--client and server-- in a secure channel--https-- anyway.

**Comment by sungwoncho** [comment]
## Changes needed to support e2e

* Login needs to change. We can no longer rely on user's API key because we need to derive a secret key from the information that only a user knows, namely the email and password combination.
* Social logins will need to be phased out and give way to email/password login.
* Password reset will be impossible. Probably we can challenge the user for password from time to time as a reminder.
* Public note cannot be supported.
* Notes cannot be directly embedded in the email digest. Rather, we will need to generate a link that requires authentication and contains the digest.
* Endpoints probably does not need to change much, because the only change is that the client will send encrypted data. So making v2 api is probably not worthwhile. But to accommodate the old, unencrypted notes, the client should probably pass an optional flag in the payload (encrypted: bool) and the server should store the flag along the with the resource.
* Google Analytics should be dropped and replaced by some minimal, non-intrusive methods.

**Comment by michielboekhoff** [comment]
@sungwoncho - thanks for this. I love the approach, using established, good-quality cryptographic primitives.

A few notes; it seems like this model, favouring security over usability, might hamper overall adoption of dnote. Tying the secret to the password incurs various problems, as you mention - password reset being impossible and having to phase out social logins. 

Have you thought of separating the authentication and encryption mechanisms? Personally, I'd look for something standard, e.g. PGP or even generating a random key for dnote, meaning I can use my external credentials, which are never sent to dnote, to encrypt this data.

Public notes can still be supported by making it clear that public notes cannot, under any circumstance, be encrypted (for obvious reasons). I'm not sure as to the mechanism for public notes but I see no problem with this.

👍 about the Google Analytics.

**Comment by sungwoncho** [comment]
I have decided to go with a combination of `pbkdf2` and `hkdf` to avoid the awkwardness of deriving auth key from enc key by hashing it one time. Not a huge deal but I think it's a good design that enc key and auth key are not related at all (added as "Alternative version 2" in the proposal).

Interesting. Could you elaborate how a user might use PGP to secure Dnote? I don't have a lot of experience with it.

**Comment by michielboekhoff** [comment]
My idea is, albeit naive, something like this:

Authentication exists as it does today. This maintains the usability aspect of dnote, including social logins.

To support encryption, a note could effectively have a flag indicating its encryption status. Notes with a flag of true could never be public. dnote can be configured to be aware of the location of the PGP key pair. dnote would then use the Go standard library to encrypt the dnote and upload the resulting contents. To decrypt, dnote would decrypt the contents with the private key.

This approach is not without its drawbacks. I heard somewhere (can't find where, now) that the Go authors are considering moving the OpenPGP implementation out of the stdlib. Also, due to its lengthy history, PGP still supports some very weak ciphers. 

Benefits of this approach would be to keep authentication intact and usable, reusing an existing set of credentials and not having to do key derivation / encryption within dnote. The weak cipher issue can be circumvented if dnote picks the cipher.

**Comment by sungwoncho** [comment]
That is a thoughtful suggestion. But given the trade-off between usability and security, I think it's still worthwhile going forward with the original plan of encrypting everything with no exception. The reasons are:

* Not many users use social login. Only two users used social login to sign in since the beginning of 2019.
* It seems like no one used public notes feature since we introduced it.

Given this data, I am inclined to make the trade-off. Let's keep your suggestion in mind in case my proposal does not work out with the users.

**Comment by sungwoncho** [comment]
Implement by [v0.6.0](https://github.com/dnote/cli/releases/tag/v0.6.0). The actual implementation ended up being kind of different. It uses pdkdf and hkdf. The actual cipher key for AES256 is generated by CSPRNG. The server stores the cipher key encrypted by user's master key derived with pbkdf.

I will soon write a blog post detailing it.

**Comment by alxjsn** [comment]
Hi @sungwoncho is e2e encryption actually implemented in the publicly hosted version? A simple API request to `https://app.getdnote.com/api/notes` reveals all my notes in cleartext which should not be the case.

**Comment by sungwoncho** [comment]
Hi @alxjsn, encryption was dropped from the project (https://www.getdnote.com/blog/back-to-knowledge-base/) and will be pursued in a fork (https://github.com/nadproject/nad). Sorry for the confusion.
