### ISSUE TITLE
Improve Installation Script Methodology

### ISSUE THREAD

**Issue by khodges42** [dnote/cli#63]
Just a thought, it's pretty bad practice to ever pipe curled things into sh (as suggested in the readme). Is there a better way to approach that?

**Comment by sungwoncho** [comment]
An alternative would be to instruct users to download a binary for their platform from the [releases](https://github.com/dnote-io/cli/releases).

Currently there is nothing that stops concerned users from doing so, but if many people are concerned, we can make it clearer in the README.

**Comment by codyogden** [comment]
@sungwoncho Would [Homebrew](https://brew.sh) be an option for installation on MacOS?

**Comment by sungwoncho** [comment]
@codyogden I think so, but let us sit on it to make sure there is enough demand

**Comment by sungwoncho** [comment]
@khodges42 now the README links to the releases page.

> Otherwise, you can download the binary for your platform manually from the releases page.

@codyogden Now Dnote is available on Homebrew. (#103) Currently the formula is on https://github.com/dnote/homebrew-dnote. In the long run, we can make it a part of homebrew-core.
