### ISSUE TITLE
windows upgrade fails: can't find release

### ISSUE THREAD

**Issue by FearNotDaniel** [dnote/cli#76]
Tested on Win7/Git Bash/MINGW32:

```
$ dnote upgrade
  • current version is 0.2.0
  • latest version is 0.2.1
  ⨯ Failed to upgrade dnote: Could not find the release for windows amd64
```

**Comment by sungwoncho** [comment]
I think we need to append `.exe` to the filename here https://github.com/dnote-io/cli/blob/master/upgrade/upgrade.go#L27. I will patch it.

**Comment by sungwoncho** [comment]
I got it to find and download the latest release on Windows, but replacing the executable with the downloaded program fails only on Windows.

```
C:\Users\a\Downloads> .\dnote-windows-amd64.exe upgrade
  • current version is 0.2.2
  • latest version is 0.2.1
  • downloading: 0.2.1
  ⨯ Failed to upgrade dnote: Failed to copy binary from temporary path: rename C:\Users\a\AppData\Local\Temp/dnote_updat
e C:\Users\a\Downloads\dnote-windows-amd64.exe: The process cannot access the file because it is being used by another p
rocess.
```

The code is

https://github.com/dnote-io/cli/blob/86d75466cac10dd0fe1162a3127fff82d602a7fa/upgrade/upgrade.go#L162-L165

Could you think of any workaround for Windows?

**Comment by sungwoncho** [comment]
Upgrade command was removed in #100. Please see #96. Feedback is always welcomed.
